-- Use este script para criar a tabela de professores no Oracle
-- Lembre-se de estar conectado ao usuário/schema correto

CREATE TABLE professores (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) UNIQUE NOT NULL,
  cpf VARCHAR2(14) UNIQUE NOT NULL,
  celular VARCHAR2(20) NOT NULL,
  senha VARCHAR2(255) NOT NULL,
  is_verified NUMBER(1) DEFAULT 0 CHECK (is_verified IN (0, 1)),
  verification_code VARCHAR2(6),
  verification_attempts NUMBER(1) DEFAULT 0,
  resend_attempts NUMBER(1) DEFAULT 0,
  reset_password_token VARCHAR2(255),
  reset_password_expires TIMESTAMP,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- O comando COMMIT é importante no Oracle para salvar as alterações
COMMIT;
