-- Use este script para criar a tabela de professores no Oracle
-- Lembre-se de estar conectado ao usuário/schema correto

CREATE TABLE professores (
  Id_Professor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR2(255) NOT NULL,
  Email VARCHAR2(255) UNIQUE NOT NULL,
  Cpf VARCHAR2(14) UNIQUE NOT NULL,
  Celular VARCHAR2(20) NOT NULL,
  Senha VARCHAR2(255) NOT NULL,
  Is_Verified NUMBER(1) DEFAULT 0 CHECK (Is_Verified IN (0, 1)),
  Primeiro_Acesso NUMBER(1) DEFAULT 1 CHECK (Primeiro_Acesso IN (0, 1)),
  Verification_Code VARCHAR2(6),
  Verification_Attempts NUMBER(1) DEFAULT 0,
  Resend_Attempts NUMBER(1) DEFAULT 0,
  Reset_Password_Token VARCHAR2(255),
  Reset_Password_Expires TIMESTAMP,
  Data_Criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Instituicao (
  Id_Instituicao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR2(100) NOT NULL,
  Id_Professor NUMBER NOT NULL,
  CONSTRAINT fk_instituicao_professor FOREIGN KEY (Id_Professor)
    REFERENCES professores(Id_Professor) ON DELETE CASCADE
);

CREATE TABLE Curso (
  Id_Curso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR2(100) NOT NULL,
  Sigla VARCHAR2(10),
  Semestres NUMBER,
  Id_Instituicao NUMBER NOT NULL,
  CONSTRAINT fk_curso_instituicao FOREIGN KEY (Id_Instituicao)
    REFERENCES Instituicao(Id_Instituicao) ON DELETE CASCADE
);

CREATE TABLE Disciplina (
  Id_Disciplina NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR2(100) NOT NULL,
  Sigla VARCHAR2(10),
  Periodo VARCHAR2(20),
  Id_Curso NUMBER NOT NULL,
  CONSTRAINT fk_disciplina_curso FOREIGN KEY (Id_Curso)
    REFERENCES Curso(Id_Curso) ON DELETE CASCADE
);

CREATE TABLE Aluno (
  Matricula NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR2(100) NOT NULL
);

CREATE TABLE Turma (
  Id_Turma NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR2(100),
  Semestre VARCHAR2(50),
  Periodo VARCHAR2(50),
  Qtd_Alunos NUMBER DEFAULT 0,
  Finalizado NUMBER(1) DEFAULT 0 NOT NULL CHECK (Finalizado IN (0, 1)),
  Id_Disciplina NUMBER NOT NULL,
  CONSTRAINT fk_turma_disciplina FOREIGN KEY (Id_Disciplina)
    REFERENCES Disciplina(Id_Disciplina) ON DELETE CASCADE
);

CREATE TABLE Aluno_Turma (
  Id_Aluno_Turma NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Matricula NUMBER NOT NULL,
  Id_Turma NUMBER NOT NULL,
  Data_Matricula TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_aluno_turma_aluno FOREIGN KEY (Matricula)
    REFERENCES Aluno(Matricula) ON DELETE CASCADE,
  CONSTRAINT fk_aluno_turma_turma FOREIGN KEY (Id_Turma)
    REFERENCES Turma(Id_Turma) ON DELETE CASCADE
);

CREATE TABLE Notas (
  Id_Nota NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Pontuacao NUMBER(5,2),
  Matricula NUMBER NOT NULL,
  Id_Turma NUMBER NOT NULL,
  CONSTRAINT fk_notas_aluno FOREIGN KEY (Matricula)
    REFERENCES Aluno(Matricula) ON DELETE CASCADE,
  CONSTRAINT fk_notas_turma FOREIGN KEY (Id_Turma)
    REFERENCES Turma(Id_Turma) ON DELETE CASCADE
);

CREATE TABLE Professor_Disciplina (
  Id_Professor NUMBER NOT NULL,
  Id_Disciplina NUMBER NOT NULL,
  PRIMARY KEY (Id_Professor, Id_Disciplina),
  CONSTRAINT fk_prof_disc_prof FOREIGN KEY (Id_Professor)
    REFERENCES professores(Id_Professor) ON DELETE CASCADE,
  CONSTRAINT fk_prof_disc_disc FOREIGN KEY (Id_Disciplina)
    REFERENCES Disciplina(Id_Disciplina) ON DELETE CASCADE
);

CREATE TABLE Professor_Curso (
  Id_Professor NUMBER NOT NULL,
  Id_Curso NUMBER NOT NULL,
  PRIMARY KEY (Id_Professor, Id_Curso),
  CONSTRAINT fk_prof_curso_prof FOREIGN KEY (Id_Professor)
    REFERENCES professores(Id_Professor) ON DELETE CASCADE,
  CONSTRAINT fk_prof_curso_curso FOREIGN KEY (Id_Curso)
    REFERENCES Curso(Id_Curso) ON DELETE CASCADE
);

CREATE TABLE Componente_Nota (
  Id_Comp NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR2(100) NOT NULL,
  Sigla VARCHAR2(10),
  Descricao VARCHAR2(255),
  Peso NUMBER(4,2),
  Id_Disciplina NUMBER NOT NULL,
  Id_Professor NUMBER NOT NULL,
  CONSTRAINT fk_comp_disc FOREIGN KEY (Id_Disciplina)
    REFERENCES Disciplina(Id_Disciplina) ON DELETE CASCADE,
  CONSTRAINT fk_comp_prof FOREIGN KEY (Id_Professor)
    REFERENCES professores(Id_Professor) ON DELETE CASCADE
);

ALTER TABLE Notas
ADD (
  Id_Comp NUMBER,
  Id_Professor NUMBER,
  CONSTRAINT fk_notas_comp FOREIGN KEY (Id_Comp)
    REFERENCES Componente_Nota(Id_Comp) ON DELETE CASCADE,
  CONSTRAINT fk_notas_prof FOREIGN KEY (Id_Professor)
    REFERENCES professores(Id_Professor) ON DELETE CASCADE
);

CREATE TABLE Log_Aud_CNotas (
  Id_Log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  DataHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Acao VARCHAR2(100),
  Valor_Antigo NUMBER(5,2),
  Valor_Novo NUMBER(5,2),
  Id_Nota NUMBER NOT NULL,
  CONSTRAINT fk_log_nota FOREIGN KEY (Id_Nota)
    REFERENCES Notas(Id_Nota) ON DELETE CASCADE
);

CREATE TABLE Log_Nota_Final (
  Id_Log_Final NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  DataHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Acao VARCHAR2(100),
  Valor_Antigo NUMBER(5,2),
  Valor_Novo NUMBER(5,2),
  Matricula NUMBER NOT NULL,
  Id_Disciplina NUMBER NOT NULL,
  CONSTRAINT fk_logfinal_aluno FOREIGN KEY (Matricula)
    REFERENCES Aluno(Matricula) ON DELETE CASCADE,
  CONSTRAINT fk_logfinal_disc FOREIGN KEY (Id_Disciplina)
    REFERENCES Disciplina(Id_Disciplina) ON DELETE CASCADE
);
