import { getConnection } from '../db';

async function createTable() {
  let connection;
  try {
    connection = await getConnection();
    const createTableSQL = `
      CREATE TABLE professores (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(255) NOT NULL,
        email VARCHAR2(255) UNIQUE NOT NULL,
        telefone VARCHAR2(20) UNIQUE,
        senha VARCHAR2(255) NOT NULL,
        verificado CHAR(1) DEFAULT 'N' CHECK (verificado IN ('S', 'N')),
        data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `;
    await connection.execute(createTableSQL);
    console.log('Tabela "professores" criada com sucesso.');
  } catch (err) {
    console.error('Erro ao criar a tabela:', err);
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (err) {
        console.error('Erro ao fechar a conexão:', err);
      }
    }
  }
}

createTable();
